# Generated by Django 5.2.1 on 2025-05-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('output_data', models.TextField(blank=True, null=True)),
                ('error_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
