# Generated by Django 5.2.1 on 2025-05-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_compiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='input_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='memory_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='runtime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
