# Generated by Django 5.2.1 on 2025-05-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_compiler", "0005_problem_solve"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="submissions",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
