# Generated by Django 5.2.1 on 2025-05-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_compiler', '0002_problem_user_code_input_data_code_memory_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solve_count',
            field=models.IntegerField(default=0),
        ),
    ]
