# Generated by Django 5.2.1 on 2025-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_compiler', '0003_problem_solve_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solve_count',
            field=models.IntegerField(),
        ),
    ]
