# Generated by Django 5.2.1 on 2025-05-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("online_compiler", "0006_problem_submissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="submissions",
            new_name="sub",
        ),
    ]
